# Site settings
title: Neith Altair
description: 'Estudiante de ingenieria apasionado por los sistemas Y la ciberseguridad. 

Etichal hacking, análisis de vulnerabilidades, OSINT, pentesting entornos web y móvil, desarrollo de scripts en Bash, Python, manejo de Linux, conocimiento en tecnologías de desarrollo web.

Implementación de Python para creación de automatizaciones.'
#url: 'http://joshgerdes.com/jekyll-uno'
url: 'https://neithaltair.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Neith Altair'
  email: neith.altair.na@gmail.com
  twitter_username: 
  facebook_username: 
  github_username:  neithaltair
  linkedin_username:  neithaltair

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
